### ISSUE TITLE
What is the difference b/w segmentations and detections

### ISSUE THREAD

**Issue by vardaan123** [ggeorgak11/mapping_navigation#1]
Hi, could you explain the difference b/w semantic segmentations and detections? segmentation is of size [H, W] whereas detection is of size [H, W, no_of_classes]. I didn't find mention of these in the paper. Could you tell me how does it affect the 
equations given in the paper?

Thanks

**Comment by yimengli46** [comment]
Segmentation output is of size HxW, where each pixel value is the category label.

Object Detection output is of size HxWxno_of_classes.
Each channel represents one category, and the masked-out area in each channel is the detected bounding box.
